// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoL6lw7HZ4UlE_E7t5M7bKQoI-evh2wNk',
    appId: '1:251652691269:web:cc6a5d3806442264a15a2c',
    messagingSenderId: '251652691269',
    projectId: 'e-learning-c024a',
    authDomain: 'e-learning-c024a.firebaseapp.com',
    storageBucket: 'e-learning-c024a.firebasestorage.app',
    measurementId: 'G-7BKC21V3PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj_590Thzf2l3WWN7v9bMq4_QCq6zIzBc',
    appId: '1:251652691269:android:6a5fd5f83f03f0e4a15a2c',
    messagingSenderId: '251652691269',
    projectId: 'e-learning-c024a',
    storageBucket: 'e-learning-c024a.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoL6lw7HZ4UlE_E7t5M7bKQoI-evh2wNk',
    appId: '1:251652691269:web:8f5c7f893aa02916a15a2c',
    messagingSenderId: '251652691269',
    projectId: 'e-learning-c024a',
    authDomain: 'e-learning-c024a.firebaseapp.com',
    storageBucket: 'e-learning-c024a.firebasestorage.app',
    measurementId: 'G-LXPR6GDKTG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc1zdDdlWkyTySCNsP-LMw-v54rSS8pCw',
    appId: '1:251652691269:ios:328710b9e319d69da15a2c',
    messagingSenderId: '251652691269',
    projectId: 'e-learning-c024a',
    storageBucket: 'e-learning-c024a.firebasestorage.app',
    androidClientId: '251652691269-9snal119idpn18fkunlka8f11fdsqvc8.apps.googleusercontent.com',
    iosClientId: '251652691269-kuo75d6toiidjjjhrbrvq67laqdukus6.apps.googleusercontent.com',
    iosBundleId: 'com.example.elearnApp',
  );

}